# Generated by Django 5.1.7 on 2025-03-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='currencyusdfixing',
            options={'verbose_name': 'Фиксинг валюты в USD', 'verbose_name_plural': 'Фиксинги валют в USD'},
        ),
        migrations.AlterModelOptions(
            name='fixing',
            options={'verbose_name': 'Фиксинг', 'verbose_name_plural': 'Фиксинги'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
