# Generated by Django 5.1.7 on 2025-04-12 07:31

from django.db import migrations, models


def populate_polygon_tickers(apps, schema_editor):
    Currency = apps.get_model('fixings', 'Currency')
    for currency in Currency.objects.all():
        currency.polygonTicker = f"C:USD{currency.currency}"
        currency.save(update_fields=['polygonTicker'])


class Migration(migrations.Migration):

    dependencies = [
        ('fixings', '0002_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='polygonTicker',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тикер вида C:USD{ISO}'),
        ),
        migrations.RunPython(populate_polygon_tickers),
    ]
