# Generated by Django 5.1.7 on 2025-04-12 08:39

from django.db import migrations, models


def populate_tickers(apps, schema_editor):
    Currency = apps.get_model('fixings', 'Currency')
    for currency in Currency.objects.all():
        currency.ticker = f"{currency.currency}USD=X"
        currency.save(update_fields=['ticker'])


class Migration(migrations.Migration):

    dependencies = [
        ('fixings', '0003_currency_polygonticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='polygonTicker',
        ),
        migrations.AddField(
            model_name='currency',
            name='ticker',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тикер вида {ISO}USD=X'),
        ),
        migrations.RunPython(populate_tickers),
    ]
