# Generated by Django 5.1.7 on 2025-04-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixings', '0005_alter_currencyusdfixing_valueusd_alter_fixing_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyusdfixing',
            name='valueUSD',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True, verbose_name='Стоимость в USD'),
        ),
        migrations.AlterField(
            model_name='fixing',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True, verbose_name='Цена закрытия'),
        ),
    ]
